# Model settings
hidden_dimension: 600
latent_dimension: 128
dropout_prob: 0.5
beta: 0.2
gamma: 0.005
mixture_weights: [0.75, 0.15, 0.1]
n_enc_epochs: 3
n_dec_epochs: 1
model: RecVAE
dataset: movie

# Training Settings_basic
epochs: 100
train_batch_size: 128
learner: 'adam'
learning_rate: 0.001
neg_sampling: None # MultiVAE is a non-sampling model
eval_step: 1
stopping_step: 10
loss_decimal_place: 4
weight_decay: 0.000

#Evaluation Settings
eval_args:
    split: {"LS": 'test_only'}
    group_by: user
    order: RO
    mode: full
repeatable: False
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 10
valid_metric: Recall@10
eval_batch_size: 4096
metric_decimal_place: 4

load_col: {"inter": ["user_id", "item_id", "timestamp"], "item": ["item_id", "year", "genre", "writer", "director"]}