# Training Settings
epochs: 100
train_batch_size: 128
learner: 'adam'
learning_rate: 0.001
neg_sampling: None # MultiVAE is a non-sampling model
eval_step: 1
stopping_step: 10
loss_decimal_place: 4
weight_decay: 0.000